In [ ]:
i, j = 3, 5 #assign more than one variable in one line
print('Hello world')

In [ ]:
if i<j:
    print(f'Variable i={i} is smaller than j={j}')

In [ ]:
i, j = 3, 5
while i <= j:
    print(i)
    i += 1
print(f"Now variables are: i={i}, j={j}")

In [ ]:
# data types

print(type(5==5))
print(type(5))
print(type(5.5))
print(type('i,j,5'))
print(type([i,j,5]))
print(type((i,j,5)))
print(type({i,j,5})) # in sets check what is hashable (what does it mean)
print(type({1:i,2:j,3:5})) 

In [ ]:
# notice the space after the comma
some_list = [5==5, 5, 5.5, 'i,j,5', [i,j,5], {i,j,5}, {1:i,2:j,3:5}]
for elem in some_list:
    print(type(elem))

In [83]:
# int.__dict__
# int(2**8).bit_length()
# int(5).bit_length()

# list([4,5]).__dict__
# #list.__dict__
# #[0,1,5].__len__() == len([0,1,5])

In [118]:
#compare:
true_or_false_list = [
    False.__and__(True) == False or True,
    (False.__and__(True)) == False or True,
    
    False.__and__(True) == (False or True),
    (False.__and__(True)) == (False or True),
    
    (False.__and__(True)) == (False.__and__(True)),
    (False or True) == (False or True),
    
    (False.__and__(True)) is (False or True),
    (False or True) is False.__and__(True)]
for elem in true_or_false_list:
    print(elem)
    
print('\n')
true_or_false_list_2 = [False or True,(False or True),(False or True,)]
for elem in true_or_false_list_2:
    print(elem)

True
True
False
False
True
True
False
False


True
True
(True,)


In [191]:
# useless fun fact: python inherit from C maximum 200 nested limit ?
# https://gcc.gnu.org/onlinedocs/cpp/Implementation-limits.html
nest_level = 5
exec('print('+
     '('*nest_level+'True or False'+
     ',{1,(6,7,(7,0))})'*nest_level+
     ')')


(((((True, {1, (6, 7, (7, 0))}), {1, (6, 7, (7, 0))}), {1, (6, 7, (7, 0))}), {1, (6, 7, (7, 0))}), {1, (6, 7, (7, 0))})


In [240]:
# matrix slicing move to intro to numpy
import numpy as np
arr = np.array([i for i in range(60)]).reshape((3,2,2,5))
print(arr)
arr[0,:,:,-2:] 

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]]


 [[[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]]


 [[[40 41 42 43 44]
   [45 46 47 48 49]]

  [[50 51 52 53 54]
   [55 56 57 58 59]]]]


array([[[ 3,  4],
        [ 8,  9]],

       [[13, 14],
        [18, 19]]])

In [242]:
arr[0,0,:,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])