look at\
https://youtu.be/LrtnLEkOwFE \
https://www.youtube.com/@mCoding \
and \
https://livebook.manning.com/book/deep-learning-with-pytorch/welcome/v-13/

download vine quality dataset from page linked on the page:\
https://medium.com/analytics-vidhya/wine-quality-prediction-using-pytorch-2a291670dd66

### Encoding data

#### representing score

In [12]:
import torch
import torch.nn as nn

In [6]:
import pandas as pd
import numpy as np

In [1]:
wine_path = 'data/winequality-red.csv'

In [4]:
# load in pandas
import pandas as pd
import numpy as np
df = pd.read_csv(wine_path)
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [8]:
# load in numpy
import csv
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=",", skiprows=1)#,quotechar="'")

In [10]:
wineq_numpy

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]],
      dtype=float32)

to torch tensor

In [13]:
wineq = torch.from_numpy(wineq_numpy)
wineq

tensor([[ 7.4000,  0.7000,  0.0000,  ...,  0.5600,  9.4000,  5.0000],
        [ 7.8000,  0.8800,  0.0000,  ...,  0.6800,  9.8000,  5.0000],
        [ 7.8000,  0.7600,  0.0400,  ...,  0.6500,  9.8000,  5.0000],
        ...,
        [ 6.3000,  0.5100,  0.1300,  ...,  0.7500, 11.0000,  6.0000],
        [ 5.9000,  0.6450,  0.1200,  ...,  0.7100, 10.2000,  5.0000],
        [ 6.0000,  0.3100,  0.4700,  ...,  0.6600, 11.0000,  6.0000]])

#### representing scores
we can keep score as number or map them to high dimentional vectors (one-hot encoding)

In [17]:
data = wineq[:, :-1] # all except the last
target = wineq[:, -1].long() # transforming to integers
target.shape

torch.Size([1599])

#### one-hot encoding

In [15]:
target_onehot = torch.zeros(target.size(0),10)

In [28]:
target.unsqueeze(1)

tensor([[5],
        [5],
        [5],
        ...,
        [6],
        [5],
        [6]])

In [38]:
target_onehot.scatter_(1, target.unsqueeze(1), 1.0 )

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])